export const CATEGORY = 'CATEGORY'
export const GOODSDETAILS = 'GOODSDETAILS'
export const USERNAME = 'USERNAME'
export const ADDRESSINFO = 'ADDRESSINFO'
export const BROWSE = 'BROWSE'
export const SHOPORDERLIST = 'SHOPORDERLIST'
export const TEMPORARYADDRESS = 'TEMPORARYADDRESS'

